[tools]
node = "latest"
ruby = 'latest'
terraform = 'latest'
python = "3.11"
zig = "0.15.1"
go = "latest"
bun = "latest"
kubectl = "latest"
kind = "latest"
argocd = "latest"
argo-rollouts = "latest"
helm = "latest"
kubeseal = "latest"
tekton-cli = "latest"
